# use tiboot3.bin secure boot variant in Tezi
FIRMWARE_BINARY[0071] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0072] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0073] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0074] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0075] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0076] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
FIRMWARE_BINARY[0221] := "tiboot3-am62x-${SYSFW_SUFFIX}-verdin.bin"
